version: "3"
services:
  bucket:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - ~/MicroSuite:/home/data
    expose:
        - "50050"
    cap_add:
        - SYS_PTRACE
    deploy:
        restart_policy:
                condition: none
        placement:
                constraints: ["node.hostname == ${NODE2}"]
    command: >
        bash -c "wget https://akshithasriraman.eecs.umich.edu/dataset/SetAlgebra/wordIDs_mapped_to_posting_lists.txt
                sudo apt-get update
                sudo apt-get install -y linux-tools-5.4.0-164-generic
                sudo apt-get install -y linux-cloud-tools-5.4.0-164-generic
                mv ./wordIDs_mapped_to_posting_lists.txt /home
                rm /home/setalgebra_shrad*.txt;shrads_num=10;split -d --additional-suffix=.txt -l $$(($$(($$(wc -l < /home/wordIDs_mapped_to_posting_lists.txt)+shrads_num-1))/shrads_num)) /home/wordIDs_mapped_to_posting_lists.txt /home/setalgebra_shrad
                shuf -n 100 /home/wordIDs_mapped_to_posting_lists.txt > /home/setalgebra_query_set.txt
                cd /MicroSuite/src/SetAlgebra/intersection_service/service/
                ./intersection_server 0.0.0.0:50050 /home/setalgebra_shrad00.txt 1 1 1"

  midtier:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - ~/MicroSuite:/home/data
    expose:
        - "50051"
    cap_add:
        - SYS_PTRACE
    deploy:
        restart_policy:
                condition: none
        placement:
                constraints: ["node.hostname == ${NODE1}"]
    command: >
        bash -c "cd /MicroSuite/src/SetAlgebra/union_service/service/
                sudo apt-get update
                sudo apt-get install -y linux-tools-generic
                sudo apt-get install -y linux-cloud-tools-generic 
                sudo apt-get install -y linux-tools-5.4.0-164-generic
                sudo apt-get install -y linux-cloud-tools-5.4.0-164-generic
                while ! echo exit | nc bucket 50050; do sleep 1; done
                echo 'bucket launched'
                touch lookup_servers_IP.txt
                echo "bucket:50050" > lookup_servers_IP.txt
                ./mid_tier_server 1 lookup_servers_IP.txt 0.0.0.0:50051 1 1 1"

  client:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - ~/MicroSuite:/home/data
    cap_add:
        - SYS_PTRACE
    deploy:
        restart_policy:
                condition: none
        placement:
                constraints: ["node.hostname == ${NODE0}"]
    command: >
        bash -c "
                wget https://akshithasriraman.eecs.umich.edu/dataset/SetAlgebra/wordIDs_mapped_to_posting_lists.txt
                sudo apt-get update
                sudo apt-get install -y linux-tools-generic
                sudo apt-get install -y linux-cloud-tools-generic 
                sudo apt-get install -y linux-tools-5.4.0-164-generic
                sudo apt-get install -y linux-cloud-tools-5.4.0-164-generic
                mv ./wordIDs_mapped_to_posting_lists.txt /home
                shuf -n 100 /home/wordIDs_mapped_to_posting_lists.txt > /home/setalgebra_query_set.txt


                cp /home/data/src/SetAlgebra/load_generator/load_generator_open_loop.cc /MicroSuite/src/SetAlgebra/load_generator/load_generator_open_loop.cc
                cp /home/data/src/SetAlgebra/load_generator/helper_files/loadgen_union_client_helper_singlenode.cc /MicroSuite/src/SetAlgebra/load_generator/helper_files/loadgen_union_client_helper_singlenode.cc
                cp /home/data/src/SetAlgebra/load_generator/helper_files/loadgen_union_client_helper.cc /MicroSuite/src/SetAlgebra/load_generator/helper_files/loadgen_union_client_helper.cc
                cd /MicroSuite/src/SetAlgebra/load_generator
                make clean
                make

                
                while ! echo exit | nc midtier 50051; do sleep 1; done
                echo 'midtier launched'
                mkdir ./results
                ./load_generator_open_loop /home/setalgebra_query_set.txt ./results 68 3500 midtier:50054"
